kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "datahub-down.name" . }}
  labels:
    {{- include "datahub-down.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  - "nodes"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - extensions
  resourceNames:
  - {{ template "datahub-down.name" . }}
  resources:
  - podsecuritypolicies
  verbs:
  - use